env:
  browser: true
  commonjs: true
  es6: true
extends:
  - airbnb-base
  - plugin:jest/recommended
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  'no-console': 'off'
  'prefer-destructuring': 'off'
plugins:
  - jest
