name: 'Check Version'
description: 'Check the version type and enforce the value if that option is specified.'
inputs:
  enforce:
    description: 'If this is set to true, the action will fail if a version type is not specifed.'
    required: false
    default: false
outputs:
  VERSION_UPPER:
    description: 'Version type in uppercase'
  VERSION_LOWER:
    description: 'Version type in lowercase'
runs:
  using: 'node12'
  main: 'index.js'
